config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'welcome#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

	CLASS_LIST = ["Ethan", "Glenn", "Haley"]

	WEEK_LIST = ["Monday", "Tuesday", "Wednesday",
        "Thursday", "Friday", "Saturday", "Sunday"]

    DATE_LIST = ["1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "8th", "9th", "10th", "11th", "12th", "13th", "14th", "15th", "16th", "17th", "18th", "19th", "20th", "21st", "22nd", "23rd", "24th", "25th", "26th", "27th", "28th", "29th", "30th", "31st"]




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
    	@articles = Article.all
  	end

	def show
   		@article = Article.find(params[:id])
  	end

	def new
  	end

	
	def create
	  @article = Article.new(article_params)
	 
	  @article.save
	  redirect_to action: "index"
	end
	 
	private
	  def article_params
	  params.require(:article).permit(:title, :text, :class_name, :week_name, :date_name)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<div class="louieHistory1"> <%= link_to 'New article', new_article_path %> </div>
<div class="middleSection1">

<table>
<!--   <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr> -->
 
  <% @articles.each do |article| %> 
    <tr>
      <td>Louie has been fed by <%= article.class_name %>
      on <%= article.week_name %>
      the <%= article.date_name %></td>

        </tr>

  
  <% end %>
</div>
</table>

app/views/articles/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Louie App</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
  <div id="boxy"> 
  <div>
    <h1 class="title-container">Fed Or Not<i class="fa fa-paw"></i></h1>
<br><br>
  </div><br>

<div class="louieHistory">
  <a href="/articles">Louie History</a>
</div>

  <div class="middleSection">
    <%= form_with scope: :article, url: articles_path, local: true do |form| %> 

      <tr>
        <td>

          Louie has been fed by <br><span> <%= form.select(:class_name, (Article::CLASS_LIST), {}, {class: "btn-primary1"}) %></span>
        

        </td><br>
        <td>on <br> <span><%= form.select(:week_name, (Article::WEEK_LIST), {}, {class: "btn-primary2"}) %></span></td><br>
        <td>the <br> <span> <%= form.select(:date_name, (Article::DATE_LIST), {}, {class: "btn-primary3"}) %></span></td><br><br>
        <td><span><%= form.submit "Submit", class: "btn-primaryOne" %></span></td>
      </tr>

    <% end %>



</div>
</body>
</html>

  

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<p>
  <strong>Who?:</strong>
  <%= @article.class_name %>
</p>

<p>
  <strong>Day</strong>
  <%= @article.week_name %>
</p>

<a href="new">Add New Louie Entry</a>


<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LouieFinalAppRepository</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1> Home Page </h1>

<a href="articles/new">New</a>